version: '3'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  web:
    build: app
    volumes:
      - ./app:/code
    ports:
      - 5000:5000
    links:
      - mongo
    depends_on:
      - mongo
  cron:
    build: cron
    volumes:
      - ./cron:/code
    links:
      - mongo
    depends_on:
      - mongo
