version: '3'

services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
  web:
    build: app
    volumes:
    - ./app:/code
    ports:
    - "5000:5000"
    depends_on:
    - mongo
    links:
    - mongo
  cron:
    build: cron
    volumes:
    - ./cron:/code
    depends_on:
    - mongo
    links:
    - mongo
